name: yet_another_hydrated_state_holder
description: Yet another hydrated state holder.
version: 0.2.0
repository: https://github.com/martinsellergren/yet_another_state_holder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  hive_ce: ^2.0.0
  yet_another_state_holder: ^0.5.0

dev_dependencies:
  test: ^1.25.6
  flutter_lints: ^6.0.0
